### ISSUE TITLE
Top10

### ISSUE THREAD

**Issue by crymis** [flash1293/rmt#1]
On the main page, show the top 10 rated trees!
Idea: mark the top 3 separately with gold, silver and bronce. (bigger images for these?!)
The other 7 listes below like it already is. Add pages on buttom to see more. (10 trees per site)

Later: Add possibilty to filter after criteria: newest, best...

**Comment by flash1293** [comment]
Check this out: http://rmt.flash1293.de 
gold/silver/bronce-trees: nice idea, please make a spearate issue
