### ISSUE TITLE
Seite funktioniert nicht inm Firefox

### ISSUE THREAD

**Issue by pongo710** [flash1293/rmt#15]
Die Seite funktioniert nicht im Firefox, weil dieser keine gemischten Inhalte zulässt.

Das bedeutet, wenn die Seite über https angesprochen wird und anderen Content über Http nachladen wird, wird das unterbunden.
https://developer.mozilla.org/de/docs/Sicherheit/MixedContent

Dieses Verhalten scheint nur im Firefox zu existieren. Chrome, Safari und Opera funktionieren.

Ist es sinnvoll im Backend direkt auch auf Https umzustellen?

(Habe die Issue mal hier aufgemacht, weil es das Frontend betrifft)

**Comment by flash1293** [comment]
Ich würde sagen das kann man erstmal vergessen, da jetzt alles über HTTP ausgeliefert wird. ich mache mal eine neue Issue auf, alles auf HTTPS umzustellen. Ist aber Prio B
